Urso.Core.Modules.Objects.Models = {
    AtlasImage: require('./atlasImage.js'),
    BitmapText: require('./bitmapText.js'),
    Button: require('./button.js'),
    ButtonComposite: require('./buttonComposite.js'),
    Checkbox: require('./checkbox.js'),
    Collection: require('./collection.js'),
    Component: require('./component.js'),
    Container: require('./container.js'),
    DragContainer: require('./dragContainer.js'),
    Emitter: require('./emitter.js'),
    EmitterFx: require('./emitterFx.js'),
    Graphics: require('./graphics.js'),
    Group: require('./group.js'),
    HitArea: require('./hitArea.js'),
    Image: require('./image.js'),
    ImagesAnimation: require('./imagesAnimation.js'),
    Mask: require('./mask.js'),
    NineSlicePlane: require('./nineSlicePlane.js'),
    Scrollbox: require('./scrollbox.js'),
    Slider: require('./slider.js'),
    Spine: require('./spine.js'),
    Text: require('./text.js'),
    TextInput: require('./textInput.js'),
    Toggle: require('./toggle.js'),
    World: require('./world.js')
};
